## TASKS

- Step 1: Load Dataset
- Step 2: Data Cleaning and checking data properties
- Step 3 : Data encoding – Map as you would like, just to convert string to numbers

iris['species'] = iris['species'].map({'Iris-setosa':0,'Iris-versicolor':1, 'Iris-virginica':2})

- Step 4 : Split Data 
- Step 5 Train, print out accuracy and confusion matrix Using 

- i.	Logistic regression
- ii.	Random forest classifier
- iii.	Gradient boosting classifier
- iv.	KNN
- v.	SVM

- Step 6 : Note the models with the best accuracy and least confusion


In [ ]:
# Import the neccessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split    

In [ ]:
#load the dataset
#view the first 5 rows of the dataset
iris = pd.read_csv('iris.csv')
print(iris.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [ ]:
#check data properties
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [62]:
iris.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667
std,0.828066,0.433594,1.764420,0.763161
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [63]:
iris.shape

(150, 5)

In [64]:
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [65]:
iris['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
#encode the target variable
iris['species'] = iris['species'].map({'Iris-setosa':0,'Iris-versicolor':1, 'Iris-virginica':2})
iris.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


### Split Data

X = Feature (input varaible)

y = Target (what we want to predict)

In [67]:
X = iris.drop('species', axis=1)
y = iris['species']

In [68]:
X

,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [69]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [84]:
# train_test_split is used to split the dataset into training and testing sets. It takes the features (X) and target variable (y) as input, along with the test size and random state for reproducibility. The function returns four sets: X_train, y_train, X_test, and y_test.    
# - X_train: The features for the training set.
# - y_train: The target variable for the training set. 
# - X_test: The features for the testing set.
# - y_test: The target variable for the testing set.
# The test_size parameter specifies the proportion of the dataset to include in the test split (in this case, 33% for testing and 67% for training). The random_state parameter ensures that the split is reproducible, meaning that the same random state will yield the same split each time the code is run.


(X_train, X_test, y_train, y_test) = train_test_split(X,y,test_size=0.33, random_state=42)
X_train

,sepal_length,sepal_width,petal_length,petal_width
96,5.7,2.9,4.2,1.3
105,7.6,3.0,6.6,2.1
66,5.6,3.0,4.5,1.5
0,5.1,3.5,1.4,0.2
122,7.7,2.8,6.7,2.0
...,...,...,...,...
71,6.1,2.8,4.0,1.3
106,4.9,2.5,4.5,1.7
14,5.8,4.0,1.2,0.2
92,5.8,2.6,4.0,1.2


In [85]:
y_train

96     1
105    2
66     1
0      0
122    2
      ..
71     1
106    2
14     0
92     1
102    2
Name: species, Length: 100, dtype: int64

### Logistic Regression Algorithm

In [86]:
# Intstantiate/launche the LR model
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [89]:
# train the model
logreg.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [90]:
# prediction

y_pred_logreg = logreg.predict(X_test)

In [91]:
y_pred_logreg

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [97]:
# evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("accuracy_score_logreg: ", accuracy_score(y_pred_logreg, y_test))
print("\nconfusion_matrix_logreg")
print(confusion_matrix(y_pred_logreg, y_test))
print("\nclassification_report_logreg")
print(classification_report(y_pred_logreg, y_test))

accuracy_score_logreg:  1.0

confusion_matrix_logreg
[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]

classification_report_logreg
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



### Random Forest Classifier Algorithm

In [98]:
# Intstantiate/launche the LR model
from sklearn.ensemble import RandomForestClassifier 
rfc = RandomForestClassifier()

In [99]:
#train the model
rfc.fit(X_train, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [100]:
# predictions
y_pred_rfc = rfc.predict(X_test)

In [101]:
y_pred_rfc

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [102]:
# evaluation

print("accuracy_score_rfc: ", accuracy_score(y_pred_rfc, y_test))
print("\nconfusion_matrix_rfc")
print(confusion_matrix(y_pred_rfc, y_test))
print("\nclassification_report_rfc")
print(classification_report(y_pred_rfc, y_test))

accuracy_score_rfc:  0.98

confusion_matrix_rfc
[[19  0  0]
 [ 0 15  1]
 [ 0  0 15]]

classification_report_rfc
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        15

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



### Gradient Boosting Classifier Algrithm

In [105]:
# Intstantiate/launche the gbc model
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()

In [106]:
#train the model
gbc.fit(X_train, y_train)

,loss,'log_loss'
,learning_rate,0.1
,n_estimators,100
,subsample,1.0
,criterion,'friedman_mse'
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_depth,3
,min_impurity_decrease,0.0
,init,None


In [107]:
#prediction
y_pred_gbc = gbc.predict(X_test)

In [108]:
y_pred_gbc

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [109]:
#evaluation

print("accuracy_score_gbc: ", accuracy_score(y_pred_gbc, y_test))
print("\nconfusion_matrix_gbc")
print(confusion_matrix(y_pred_gbc, y_test))
print("\nclassification_report_gbc")
print(classification_report(y_pred_gbc, y_test))

accuracy_score_gbc:  0.98

confusion_matrix_gbc
[[19  0  0]
 [ 0 15  1]
 [ 0  0 15]]

classification_report_gbc
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        15

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



### K Nearest Neighbors (KNN) Algorithm

In [110]:
# Intstantiate/launche the knn model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [111]:
#train the model
knn.fit(X_train, y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [112]:
#prediction
y_pred_knn = knn.predict(X_test)

In [114]:
y_pred_knn

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [116]:
#evaluate

print("accuracy_score_knn: ", accuracy_score(y_pred_knn, y_test))
print("\nconfusion_matrix_knn")
print(confusion_matrix(y_pred_knn, y_test))
print("\nclassification_report_knn")
print(classification_report(y_pred_knn, y_test))


accuracy_score_knn:  0.98

confusion_matrix_knn
[[19  0  0]
 [ 0 15  1]
 [ 0  0 15]]

classification_report_knn
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        15

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



### Support Vector Machine (SVM) Algorithm

In [117]:
#instantiate/launche the svm model
from sklearn.svm import SVC
svm = SVC(kernel='rbf')

In [118]:
#train the model
svm.fit(X_train, y_train)

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [119]:
#prediction
y_pred_svm = svm.predict(X_test)

In [120]:
y_pred_svm

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [121]:
#evaluate
print("accuracy_score_svm: ", accuracy_score(y_pred_svm, y_test))
print("\nconfusion_matrix_svm")
print(confusion_matrix(y_pred_svm, y_test))
print("\nclassification_report_svm")
print(classification_report(y_pred_svm, y_test))

accuracy_score_svm:  1.0

confusion_matrix_svm
[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]

classification_report_svm
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



#### Final note

The models with the best accuracy and least confusion are: 
***Logistic regression***
and
***Support vector machine (SVM)***